  CLASSGROUP "natura2000:lnv_natura2000"
  CLASSITEM "bescherming"
  CLASS
    NAME "HR"
    GROUP "natura2000:lnv_natura2000"
    EXPRESSION "HR"
    STYLE
      COLOR 230 230 0
    END
  END
  CLASS
    NAME "VR"
    GROUP "natura2000:lnv_natura2000"
    EXPRESSION "VR"
    STYLE
      COLOR 190 230 255  
    END
  END
  CLASS
    NAME "VR+HR"
    GROUP "natura2000:lnv_natura2000"
    EXPRESSION "VR+HR"
    STYLE
      COLOR 210 255 115	  
    END
  END
  CLASS
    NAME "HR groeve"
    GROUP "natura2000:lnv_natura2000"
    EXPRESSION "HR groeve"
    STYLE      
      OUTLINECOLOR 0 0 0
	  WIDTH 1.0 	  
    END
	STYLE
	  SYMBOL "hatchsymbol"
	  COLOR 255 125 0
	  SIZE 10
	  WIDTH 1
	END
	STYLE
	  SYMBOL "hatchsymbol"
	  COLOR 255 125 0
	  SIZE 10
	  WIDTH 1	  
	  ANGLE 90
	END
  END  